language: java

git:
  depth: false

addons:
  sonarcloud:
    organization: "kreait"
    token:
      secure: $SONAR_TOKEN
  apt:
    packages:
      - openjdk-6-jdk

services:
  - docker

dist: trusty

jdk:
  - openjdk8

os:
  - linux



branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

stages:
  - test
  - publish
  - publish_docker

jobs:
  include:
    - stage: test
      name: "PullRequest Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube -Dslack.test.integration.token=$TEST_SLACK_SPACE_TOKEN -Dslack.test.integration.build=$TRAVIS_BUILD_NUMBER -Dslack.security.signing-secret=$TEST_SLACK_SPACE_SIGNING --info --scan
      if: type = pull_request

    - stage: test
      name: "Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube -Dsonar.login=$SONAR_TOKEN -Dslack.test.integration.token=$TEST_SLACK_SPACE_TOKEN -Dslack.test.integration.build=$TRAVIS_BUILD_NUMBER -Dslack.security.signing-secret=$TEST_SLACK_SPACE_SIGNING --info --scan
      if: branch = master AND type != pull_request

    - stage: publish
      name: "Publish Library"
      script: ./gradlew publish
      if: branch = master AND type != pull_request

    - stage: publish_docker
      name: "Publish Docker"
      env:
        - DOCKER_IMAGE_BASE_TAG=kreait/slack-spring-boot-starter
        - SAMPLE_PATH=samples/slack-spring-boot-starter-sample
      script:
        - VERSION=($(cat version.txt))
        - cd $SAMPLE_PATH
        - docker build -t $DOCKER_IMAGE_BASE_TAG:$VERSION -t $DOCKER_IMAGE_BASE_TAG:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMAGE_BASE_TAG:$VERSION
        - docker push $DOCKER_IMAGE_BASE_TAG:latest



