language: java

addons:
  sonarcloud:
    organization: "olaph-io"
    token:
      secure: $SONAR_TOKEN


jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      name: "PullRequest Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube --info
      if: type = pull_request

    - stage: test
      name: "Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube -Dsonar.login=$SONAR_TOKEN --info
      if: branch = master AND type != pull_request

    - stage: publish
      name: "Publish Library"
      script: ./gradlew publish
      if: branch = master AND type != pull_request
