language: java

git:
  depth: false

addons:
  sonarcloud:
    organization: "olaph-io"
    token:
      secure: $SONAR_TOKEN


jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      name: "PullRequest Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube -Dslack.test.integration.token=$TEST_SLACK_SPACE_TOKEN -Dslack.test.integration.build=$TRAVIS_BUILD_NUMBER -Dslack.security.signing-secret=$TEST_SLACK_SPACE_SIGNING --info --scan
      if: type = pull_request

    - stage: test
      name: "Quality Check and Tests"
      script: ./gradlew check jacocoTestReport sonarqube -Dsonar.login=$SONAR_TOKEN -Dslack.test.integration.token=$TEST_SLACK_SPACE_TOKEN -Dslack.test.integration.build=$TRAVIS_BUILD_NUMBER -Dslack.security.signing-secret=$TEST_SLACK_SPACE_SIGNING --info --scan
      if: branch = master AND type != pull_request

    - stage: publish
      name: "Publish Library"
      script: ./gradlew publishclient/slack-spring-api-client/src/main/kotlin/io/olaph/slack/client/spring/group/conversations/DefaultConversationsMethodGroup.kt
      if: branch = master AND type != pull_request
